version: '3.0'

services:
  kasm_app:
    image: kasmweb/ubuntu-focal-desktop:1.13.0
    deploy:
      replicas: 3
    shm_size: 512m
    ports:
      - "6901:6901"
    environment:
      - VNC_PW=password

